name = "PeriodicGraphEmbeddings"
uuid = "f305370e-dc8e-427a-bb15-d3949eabeccf"
authors = ["Lionel Zoubritzky <lionel.zoubritzky@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
